### ISSUE TITLE
ScaleUp 

### ISSUE THREAD

**Issue by pablo-hidalgoo** [LancerComet/Lancercomet.NET#2]
I have one question about ScaleUp but I cannot find a repository for it. Where can I ask you about it? Thanks!

**Comment by LancerComet** [comment]
Oh I've forgotten to open a repo for ScaleUp, it's fine to ask me here @pablo-hidalgoo

**Comment by pablo-hidalgoo** [comment]
Okey! On windows 10, when clicking on the folder icon, nothing happens

**Comment by LancerComet** [comment]
Clicking folder icon should launch system folder selector, once a folder has been selected, "Rock n' roll" button should be light up.
I will check it out soon, thanks for your feedback

**Comment by LancerComet** [comment]
> Okey! On windows 10, when clicking on the folder icon, nothing happens

Fixed. I will upload a new version very soon. Tested on Windows 10 22H2 10945.2965

**Comment by pablo-hidalgoo** [comment]
Cool, Thank you! It seems to be the old version yet. Will you be notified when the update is available? Can you answer this message when it is available so I can check if it is working now? Thank you!

**Comment by LancerComet** [comment]
New version is online, v0.1.1 @pablo-hidalgoo

**Comment by LancerComet** [comment]
I am closing this issue. Please reopen it if you encounter a new issue.
